config/routes.rb
Rails.application.routes.draw do

  get 'home/about'=>'homes#about'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'

  resources :users, only: [:index, :show, :edit, :update] 

  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]

  resources :homes, only: [:top, :about]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user

	validates :title, presence: true
	validates :body, presence: true
	validates :body, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  attachment :profile_image
  attachment :image

  validates :introduction, length: { maximum: 50 }
  validates :name, length: { in: 2..20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	

	def after_sign_in_path_for(resource)
		flash[:notice] = "successfully"
		user_path(current_user)
	end
	def after_sign_out_path_for(resource)
		flash[:notice] = "Signed out successfully."
    	root_path
  	end
	protected
	  def configure_permitted_parameters
	    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])	  
	  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	before_action :correct_user, only: [:edit]
	
	def index
		@book = Book.new
		@books = Book.all
		@user = current_user
	end

	def create
		@books = Book.all
		@user = current_user
		@book = Book.new(book_params)
	    @book.user_id = current_user.id
	    if @book.save
	    	flash[:notice] = "successfully"
	    	redirect_to book_path(@book.id)
		else
			render :index
		end

	end

	def new	

	end

	

	def show
		@book_new = Book.new
		@book = Book.find(params[:id])
		#@user = User.find(params[:books_user_id])
		

		
			
	end	

	def edit
		@book = Book.find(params[:id])
	end

	
	def update
	  	@book = Book.find(params[:id])
	  	if @book.update(book_params)
	  		flash[:notice] = "successfully"
	  		redirect_to book_path(@book.id)
	  	else
	  		flash[:notice] = "error"
	  		render :edit
	  	end
  	end

	def destroy
		book = Book.find(params[:id])
        book.destroy
        redirect_to books_path
	end




private
    def book_params
        params.require(:book).permit(:title, :body)
    end

    def correct_user
    book = Book.find(params[:id])
    if current_user != book.user
      redirect_to books_path
    end
  	end
	
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
before_action :correct_user, only: [:edit, :update]


  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new
		
  end

  def index
  	@users = User.all
  	@user = current_user
  	@book = Book.new
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		flash[:notice] = "successfully"
  		redirect_to user_path(@user.id)
  	else
  		render :edit
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new.html.erb
<%= form_for(book, url: books_path) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= book.errors.count %>件のerrorが発生しました。</h2>
      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <h2>New book</h2>
  <div class="row">
    <div>
      <div class="form-group has-icon">
        <h4>Title</h4>
        <%= f.text_field :title, class:"form-control", placeholder:"Title" %>
        <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
      </div>
    </div>
  </div>
  <div class="row">
    <div>
      <h4>Opinion</h4>
      <%= f.text_area :body, class:"form-control", rows:"3", placeholder:"Body" %>
    </div>
  </div>
  <div class="row createbook">
  <%= f.submit "Create Book", class:"btn btn-primary btn-md btn-block btn-base-1 mt-20" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="body-wrap">
  <div id="st-container" class="st-container">
    <div class="st-pusher">
      <div class="st-content">
        <div class="st-content-inner">      
          <section class="slice slice-lg sct-color-1">
              <div class="container">
                  <div class="row">
                      <div class="col-md-4 col-md-offset-4">
                          <div class="form-user style-1 rounded has-shadow-1"> 
                            <div class="form-header text-center">
                                <h2 class="form-header-title">Editing Book</h2>
                            </div>
                            <div class="form-body">
                              <%= form_for(@book) do |f| %>
                                <div class="form-group has-icon">
                                    <label class="control-label sr-only" for="inputEmail">Title</label>
                                    <%= f.text_field :title, autofocus: true, class:"form-control", id:"inputEmail", placeholder:""%>
                                    <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
                                </div>                               
                                <div class="form-group has-icon">
                                    <label class="control-label sr-only" for="inputEmail">Opinion</label>
                                    <%= f.text_field :body, autofocus: true, class:"form-control", id:"inputEmail", placeholder:""%>
                                    <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
                                </div>                      
                                <%= f.submit "Update Book", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
                            <% end %>
                            <span><%= link_to "Show", book_path(@book) %></span>
                            <span><%= link_to "Back", books_path %></span>
                              <!-- ここにform_forを追加します -->
                            </div>
                          </div> 
                      </div>
                  </div>
              </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">

<%= render 'users/userinfo', user: @user %>
<%= render 'books/new', book: @book %>

    </div>
    <div class="col-xs-9">
  <h2>Book2</h2>
 <table class="table">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to(user_path(book.user_id)) do %>
            <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size: "40x40"%></td>
          <% end %>

          
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= book.body %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  
    </div>
  </div>
</div>



  

app/views/books/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<%= render 'users/userinfo', user: @book.user %>
			<%= render 'books/new', book: @book_new %>
		</div>
		<div class="col-xs-9">
		<h2>Book detail</h2>
		 <table class="table">
		    <tbody>
		      <tr>
		        <td><%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" %><span><%= link_to @book.user.name, user_path(@book.user_id) %></span></td>
		        <td><%= @book.title %></td>
		        <td><%= @book.body %></td>
		        <% if current_user == @book.user %>
			        <td><%= link_to "Edit", edit_book_path(@book.id) %></td>
			        <td><%= link_to "Destroy", book_path(@book), method: :delete %></td>
			    <% end %>
		      </tr>
		    </tbody>
		  </table>
		</div>
	</div>
  </div>

app/views/homes/about.html.erb
<div class="top-message col-md-offset-1 col-md-6">	
<h1>Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers!</h1>
</div>

app/views/homes/top.html.erb
<div class="container">
	<div class="row">
		<div class="top-message col-md-offset-3 col-md-6">
			
<h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers !!</h1>

<p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers,<br>

you can share and exchange your opinions , inpressions , and emotions<br>

about various books!</p>

<p class="btn btn-info col-xs-10 col-xs-offset-1">
	<%= link_to "Log in", user_session_path %>
</p>
<p class="btn btn-success col-xs-10 col-xs-offset-1 sign_up">
<%= link_to "Sign up", new_user_registration_path %>
</p>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar-fixed-top">
    <nav class="navi navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <h3 class="nav_title">Bookers</h3>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <li class="active">       
        <%= link_to(user_path(current_user.id)) do %>
        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
        <span>Home</span>
        <% end %>     
      </li>
      <li>
        <%= link_to(users_path) do %>
        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
        <span>Users</span>
        <% end %>
      </li>
      <li>
        <%= link_to(books_path) do %>
        <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
        <span>Books</span>
        <% end %>
      </li>
      <li>
        <%= link_to(destroy_user_session_path, method: :delete) do %>
        <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
        <span>logout</span>
        <% end %>
      </li>
      <% else %>
      <li>
        <%= link_to(root_path) do %>
        <span>Home</span>
        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
        <% end %>
      </li>

      <li>
        <%= link_to(home_about_path) do %>
        <span>About</span>
        <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
        <% end %>
      </li>

      <li>
        <%= link_to(new_user_registration_path) do %>
        <span>sign up</span>
        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
        <% end %>
      </li>
      <li>
        <%= link_to(new_user_session_path) do %>
        <span>login</span>
        <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
        <% end %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>
</div>

    <% if flash[:notice] %>
    <div class="flash">
      <%= flash[:notice] %>
    </div>
  <% end %>
  
    <%= yield %>
  </body>
</html>

app/views/users/_userinfo.html.erb
<h2>User info</h2>
<table class="table">		
			<p><%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></p>
		</tr>
	<tbody>
		<tr><td>name</td>
			<td><%= user.name %></td>
		</tr>
		<tr>
			<td>introduction</td>
			<td><%= user.introduction %></td>
		</tr>
	</tbody>
</table>	
		<% if user.id == current_user.id %>
			<p>
				<%= link_to "", edit_user_path(current_user.id), class: "btn btn-default glyphicon glyphicon-wrench btn-xs btn-block" %>
			</p>
		<% else %>
			<p>
				<%= link_to "", user_path(current_user.id), class: "btn btn-default glyphicon glyphicon-wrench btn-xs btn-block" %>
			</p>
		<% end %>
		

app/views/users/edit.html.erb
<div class=container>
  <div class="row">
    <div coass="col-lg-9">         
    <h2>User info</h2>
    <div>
      <%= form_for(@user) do |f| %>
      <% if f.object.errors.any? %>
        <div id="error_explanation">
          <h2><%= f.object.errors.count %>件のerrorーが発生しました。</h2>
          <ul>
          <% f.object.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

        <div>
            <label>Name</label>
            <%= f.text_field :name, id:"inputEmail", placeholder:""%>
        </div>
        <div>                                    
            <label>Image</label>
            <%= f.attachment_field :profile_image, placeholder: "" %>
        </div>                                
        <div>
            <label>Introduction</label>
            <%= f.text_area :introduction, id:"inputEmail", placeholder:""%>
        </div>                      
        <%= f.submit "Update User", class:"btn btn-default btn-xs" %>
    <% end %>
    </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">    
      <%= render 'users/userinfo', user: @user %>
      <%= render 'books/new', book: @book %> 
    </div>
    <div class="col-xs-9"> 
      <h2>Users</h2>     
       <table class="table">
          <thead>
            <tr>            
              <th>Image</th>
              <th>Name</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>
              
              <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg",size: "40x40" %>
              </td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div> 
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <%= render 'users/userinfo', user: @user %>
      <%= render 'books/new', book: @book %>       
    </div> 
    <div class="col-xs-9">
       <h2>Books</h2>
       <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td><%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size: "40x40" %></td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
            </tr>
            <% end %>
          </tbody>
        </table>  
      </div>
    </div>   
  </div> 
</div>